Update index.d.ts (Fix ref attribute is missing)
In 1.0.32, below code shows error when running typescript compiler (tsc).
```
error TS2322: Type '{ ref: (ref: any) => number; style: ViewStyle; }' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.

30         <ShimmerPlaceHolder ref={(ref) => this.animationRefs.push(ref)} style={styles.booklistImage} />
            ~~~~~~~~~~~~~~~~~~
```

In this project's d.ts file defined `ShimmerPlaceHolder` as SFC but it doesn't have ref attribute.
This PR resolve this issue.